### ISSUE TITLE
intermittent RepositoryUnreadableError failures

### ISSUE THREAD

**Issue by timogoebel** [dm-drogeriemarkt/foreman_git_templates#44]
We see these intermittent failures. Triggering another host rebuild usually resolved the situation for some time. We should find the root cause and fix this.

```
ForemanGitTemplates::RepositoryReader::RepositoryUnreadableError: Cannot read repository from /tmp/down-net_http20190808-11579-ae5r42.gz
Errno::ENOENT: ********
  from foreman_git_templates/tar.rb:17:in `open'
  from foreman_git_templates/tar.rb:17:in `untar'
  from foreman_git_templates/repository_reader.rb:30:in `content'
  from foreman_git_templates/repository_reader.rb:11:in `call'
  from foreman_git_templates/repository_reader.rb:16:in `call'
  from foreman_git_templates/hostext/operating_system.rb:21:in `block (2 levels) in available_template_kinds'
  from foreman_git_templates/hostext/operating_system.rb:20:in `tap'
  from foreman_git_templates/hostext/operating_system.rb:20:in `block in available_template_kinds'
  from active_record/relation/delegation.rb:41:in `each'
  from active_record/relation/delegation.rb:41:in `each'
  from foreman_git_templates/hostext/operating_system.rb:19:in `map'
  from foreman_git_templates/hostext/operating_system.rb:19:in `available_template_kinds'
  from foreman_git_templates/hostext/operating_system.rb:13:in `provisioning_template'
  from app/models/concerns/orchestration/tftp.rb:132:in `validate_tftp'
  from active_support/callbacks.rb:426:in `block in make_lambda'
  from active_support/callbacks.rb:236:in `block in halting_and_conditional'
  from active_support/callbacks.rb:517:in `block in invoke_after'
  from active_support/callbacks.rb:517:in `each'
  from active_support/callbacks.rb:517:in `invoke_after'
  from active_support/callbacks.rb:133:in `run_callbacks'
  from active_support/callbacks.rb:816:in `_run_validation_callbacks'
  from active_model/validations/callbacks.rb:118:in `run_validations!'
  from active_model/validations.rb:339:in `valid?'
  from active_record/validations.rb:67:in `valid?'
  from app/models/concerns/orchestration.rb:86:in `valid?'
  from app/models/host/managed.rb:927:in `trigger_nic_orchestration'
```

**Comment by timogoebel** [comment]
We currently suspect that ruby cleans up the template that down correctly downloads because the tempfile object is garbage collected. `RepositoryFetcher` just returns the path to the tempfile so the tempfile object is not referenced anymore and thus cleaned up.

https://github.com/dm-drogeriemarkt/foreman_git_templates/blob/c0c17a0a1ebc8a21259f7827341b585a561b63ee/app/services/foreman_git_templates/repository_fetcher.rb#L12
